# Generated by Django 4.2.5 on 2023-09-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-updated_at'], 'verbose_name': 'ژانر', 'verbose_name_plural': 'ژانر ها'},
        ),
        migrations.AddField(
            model_name='actors',
            name='image',
            field=models.ImageField(null=True, upload_to='images/actor_image', verbose_name='تصویر بازیگر'),
        ),
        migrations.AddField(
            model_name='director',
            name='image',
            field=models.ImageField(null=True, upload_to='images/director_image', verbose_name='تصویر کارگردان'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(null=True, upload_to='images/video_image', verbose_name='تصویر ویدئو'),
        ),
    ]
