# Generated by Django 4.2.5 on 2023-09-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_season_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-created_at'], 'verbose_name': 'فصل ', 'verbose_name_plural': 'فصل ها'},
        ),
    ]
