# Generated by Django 4.2.5 on 2023-09-23 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_season_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='video',
            field=models.ManyToManyField(related_name='season', to='movie.video', verbose_name='ویدیوها'),
        ),
        migrations.CreateModel(
            name='Cinematic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='نام سینمایی')),
                ('image', models.ImageField(upload_to='serial', verbose_name='تصویر سینمایی ')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='اسلاگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود سینمایی ')),
                ('age', models.CharField(blank=True, choices=[('20', '+20'), ('14', '+14'), ('10', '+10')], max_length=10, null=True, verbose_name='رده سنی')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='سال ساخت سینمایی')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='movie.video', verbose_name='ویدیوها')),
            ],
            options={
                'verbose_name': 'سینمایی',
                'verbose_name_plural': 'سینمایی ها',
                'ordering': ['-created_at'],
            },
        ),
    ]
